# yaml 配置
version: '3'
services:
  server:
    build:
      context: .
    ports:
     - "8000:80"
    volumes: 
     - ./:/server
    restart: always
    depends_on: 
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'water-cycle'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'water-cycle'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'secret_secret_3412'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'secret_secret_3412'
    expose:
      - '3306'
    volumes:
      - water-cycle-db:/var/lib/mysql
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
volumes:
  water-cycle-db:
